const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const stages=$$('.stage');const analysis=$('#analysis');const sticky=$('#stickyCta');const input=$('#websiteInput');
const demo={company:{name:'Northline Commercial HVAC',url:'northlinehvac.ca',desc:'Commercial HVAC service, maintenance and retrofit support for businesses and multi-site operators across the Greater Toronto Area.',chips:['Commercial HVAC','Maintenance contracts','Retrofits','Toronto & GTA']},competitors:['ServicePro HVAC','Metro Climate Group','York Mechanical','Urban Air Systems','GTA Facility Services','Northern Comfort'],segments:[['Property managers','1.2K','Reduce HVAC downtime across multiple commercial properties.','Emergency repairs, vendor coordination and preventive maintenance'],['General contractors','840','Add a reliable HVAC partner for active construction and retrofit work.','Project delays and unreliable trade availability'],['Multi-location retailers','690','Standardize HVAC service across several GTA locations.','Different vendors and inconsistent response times'],['Warehouses & industrial','510','Keep high-load facilities operational with planned service.','Downtime creates immediate operating cost'],['Medical clinics','430','Protect comfort and uptime in patient-facing facilities.','Temperature issues disrupt patient experience and operations']],prospects:[['Summit Property Group','Richmond Hill','94','Property manager','12 commercial properties','Facilities team listed','Within service radius'],['Harbourview Asset Management','Toronto','91','Property manager','Multi-site portfolio','Recent facilities hiring','Commercial focus'],['Northcrest Builders','Vaughan','89','General contractor','Active retrofit projects','GTA project portfolio','Mechanical partners used'],['Maple Retail Holdings','Markham','87','Multi-location retailer','8 GTA locations','Central operations team','Recurring facility needs'],['Westline Logistics','Mississauga','84','Warehouse','Large industrial site','24/7 operation','HVAC uptime critical']],people:[['MP','Maya Patel','Director of Property Operations','Summit Property Group'],['JL','Jordan Lee','Facilities Manager','Harbourview Asset Management'],['AK','Aaron Kim','VP Operations','Northcrest Builders'],['SO','Sarah Osei','Director of Store Operations','Maple Retail Holdings'],['DM','Daniel Martin','General Manager','Westline Logistics']]};
function cleanDomain(v){return(v||'').trim().replace(/^https?:\/\//,'').replace(/^www\./,'').replace(/\/.*/,'')}
function labelDomain(d){if(!d)return demo.company.name;return d.split('.')[0].replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function openStage(n){stages.forEach((s,i)=>s.classList.toggle('open',i===n-1));}
function completeStage(n,html){const s=stages[n-1];s.classList.remove('active');s.classList.add('complete');$('.stage-state',s).textContent='Complete';$('.stage-body',s).innerHTML=html;if(stages[n]){stages[n].classList.add('active');$('.stage-state',stages[n]).textContent='Running';openStage(n+1)}else openStage(n)}
function companyHTML(domain){const name=labelDomain(domain);return `<div class="company-card"><div class="company-logo">${name.slice(0,2).toUpperCase()}</div><div><h3>${name}</h3><div class="url">${domain}</div></div><span class="found">✓ Found</span><p class="company-desc">${demo.company.desc}</p><div class="chips">${demo.company.chips.map(x=>`<span class="chip">${x}</span>`).join('')}</div></div>`}
function competitorsHTML(){return `<div class="grid-list">${demo.competitors.map(x=>`<div class="competitor"><b>${x}</b><span>↗</span></div>`).join('')}</div>`}
function segmentsHTML(){return `<div class="segment-stack">${demo.segments.map(x=>`<article class="segment-card"><div class="segment-top"><h3>${x[0]}</h3><span class="market-size">${x[1]}</span></div><p>${x[2]}</p><span class="pain"><b>PAIN</b><br>${x[3]}</span></article>`).join('')}</div>`}
function prospectsHTML(){return `<div class="prospects">${demo.prospects.map(x=>`<article class="prospect"><div class="prospect-top"><h3>${x[0]}</h3><span class="score">${x[2]}% fit</span></div><p>${x[1]} · ${x[3]}</p><div class="evidence">${x.slice(4).map(e=>`<span>${e}</span>`).join('')}</div></article>`).join('')}</div>`}
function peopleHTML(){return `<div class="people">${demo.people.map(x=>`<div class="person"><div class="avatar">${x[0]}</div><div><strong>${x[1]}</strong><small>${x[2]} · ${x[3]}</small></div><span class="linkedin">in</span></div>`).join('')}</div>`}
function emailHTML(domain){const name=labelDomain(domain);return `<div class="email-card"><div class="email-head"><strong>Personalized draft</strong><span>Manual approval required</span></div><div class="email-body"><p><b>Subject:</b> HVAC coverage for Summit's GTA properties</p><p>Hi Maya,</p><p>I noticed Summit manages multiple commercial properties across the GTA and has an internal facilities team. ${name} supports commercial operators with preventive HVAC maintenance, emergency response and retrofit work across Toronto, York Region and Peel.</p><p>Would it be useful to compare your current coverage against a second GTA service option?</p><p>— ${name}</p></div></div>`}
async function runScan(v){const domain=cleanDomain(v)||'yourbusiness.ca';input.value=domain;analysis.classList.remove('hidden');sticky.classList.remove('hidden');$('#analysisTitle').textContent=`Mapping ${labelDomain(domain)} across the GTA`;analysis.scrollIntoView({behavior:'smooth',block:'start'});stages.forEach((s,i)=>{s.className='stage'+(i===0?' active open':'');$('.stage-state',s).textContent=i===0?'Running':'Waiting';$('.stage-body',s).innerHTML=i===0?'<div class="skeleton large"></div>':''});const jobs=[[1,companyHTML(domain),650],[2,competitorsHTML(),650],[3,segmentsHTML(),800],[4,prospectsHTML(),900],[5,peopleHTML(),850],[6,emailHTML(domain),700]];for(const [n,html,ms] of jobs){await new Promise(r=>setTimeout(r,ms));completeStage(n,html)}showToast('Market scan complete — demo data shown for the MVP.');}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3400)}
$('#scanForm').addEventListener('submit',e=>{e.preventDefault();runScan(input.value)});$('#noSiteBtn').addEventListener('click',()=>{input.value='';runScan('local-business-demo.ca')});$$('.stage-head').forEach((b,i)=>b.addEventListener('click',()=>{const s=stages[i];s.classList.toggle('open')}));function pilot(){showToast('Pilot signup is next: connect billing + Supabase workspace provisioning.')}$('#pilotBtn').addEventListener('click',pilot);$('#stickyPilot').addEventListener('click',pilot);