const UA='Mozilla/5.0 (compatible; ReadyCustomer/1.1; +https://readycustomer.ca)';

function clean(s=''){return String(s).replace(/\s+/g,' ').trim()}
function decodeHtml(s=''){return String(s).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function stripHtml(html=''){return clean(decodeHtml(String(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')))}
function normalizeUrl(v){let s=clean(v);if(!/^https?:\/\//i.test(s))s='https://'+s;return new URL(s)}
function privateHost(h){const x=h.toLowerCase();if(x==='localhost'||x.endsWith('.local')||x==='0.0.0.0'||x==='::1')return true;const m=x.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/);if(!m)return false;const a=+m[1],b=+m[2];return a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||a===0}
function safeUrl(v){const u=normalizeUrl(v);if(!['http:','https:'].includes(u.protocol)||privateHost(u.hostname))throw new Error('Unsupported website address');return u}
function hostOf(v){try{return new URL(v).hostname.replace(/^www\./,'')}catch{return null}}
function uniqBy(arr,key){const seen=new Set();return arr.filter(x=>{const k=key(x);if(!k||seen.has(k))return false;seen.add(k);return true})}
function emailsFrom(text=''){return [...new Set((String(text).match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).map(x=>x.toLowerCase()))].filter(x=>!/(example\.com|sentry|wix|cloudflare|wordpress|noreply|no-reply)/i.test(x))}

async function fetchText(url,ms=8500){const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),ms);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml,text/plain'},redirect:'follow',signal:ctrl.signal});if(!r.ok)throw new Error('HTTP '+r.status);const type=r.headers.get('content-type')||'';if(!type.includes('text/html')&&!type.includes('text/plain'))throw new Error('Unsupported content');const txt=await r.text();return {url:r.url,html:txt.slice(0,350000)}}finally{clearTimeout(t)}}

function pageFacts(page){const html=page.html;const title=clean((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||'');const md=clean(((html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i)||html.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)||[])[1]||''));const h1=[...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>stripHtml(m[1])).filter(Boolean).slice(0,4);const h2=[...html.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/gi)].map(m=>stripHtml(m[1])).filter(Boolean).slice(0,18);const links=[...html.matchAll(/href=["']([^"'#]+)["']/gi)].map(m=>m[1]).filter(Boolean);const text=stripHtml(html).slice(0,36000);return {title,description:md,h1,h2,links,text,emails:emailsFrom(html+' '+text)}}

function internalResearchLinks(facts,pageUrl,limit=4){const base=new URL(pageUrl);const scored=[];for(const href of facts.links){try{const u=new URL(href,pageUrl);if(u.hostname!==base.hostname)continue;if(/\.(pdf|jpg|jpeg|png|gif|svg|webp|zip)$/i.test(u.pathname))continue;let score=0;const p=u.pathname.toLowerCase();if(/about|company|who-we-are/.test(p))score+=5;if(/service|solution|product|practice|expertise/.test(p))score+=5;if(/industr|customer|client|case-stud|portfolio/.test(p))score+=4;if(/contact|team|people|leadership/.test(p))score+=3;if(score)scored.push({u,score})}catch{}}
return uniqBy(scored.sort((a,b)=>b.score-a.score),x=>x.u.href).slice(0,limit).map(x=>x.u)}

async function crawlBusiness(url){const first=await fetchText(safeUrl(url).href);const firstFacts=pageFacts(first);const targets=internalResearchLinks(firstFacts,first.url,4);const extra=await Promise.allSettled(targets.map(u=>fetchText(u.href,6000)));const pages=[{url:first.url,facts:firstFacts}];for(const r of extra)if(r.status==='fulfilled')pages.push({url:r.value.url,facts:pageFacts(r.value)});return pages}

async function aiJSON(prompt){const token=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;if(!token)return null;for(const model of ['openai/gpt-5.6-luna','google/gemini-2.5-flash-lite']){try{const r=await fetch('https://ai-gateway.vercel.sh/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({model,temperature:0.15,response_format:{type:'json_object'},messages:[{role:'system',content:'You are a careful GTA go-to-market research analyst. Use only facts supplied in the prompt or facts accompanied by a source URL. Never invent a company, person, contact detail, metric, licence, permit, review, or intent signal. Mark unknown values as null. Keep Canadian outreach compliance risks visible. Return valid JSON only.'},{role:'user',content:prompt}]})});if(!r.ok)continue;const j=await r.json();const s=j?.choices?.[0]?.message?.content;if(!s)continue;return JSON.parse(s.replace(/^```json\s*/,'').replace(/```$/,''))}catch{}}
return null}

async function searchWeb(q){try{const r=await fetch('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),{headers:{'user-agent':UA,'accept':'text/html'}});if(!r.ok)return[];const html=await r.text();const out=[];for(const m of html.matchAll(/<a[^>]+class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){let href=decodeHtml(m[1]);try{const u=new URL(href,'https://duckduckgo.com');const uddg=u.searchParams.get('uddg');if(uddg)href=decodeURIComponent(uddg)}catch{}const title=stripHtml(m[2]);if(!/^https?:/i.test(href)||!title)continue;out.push({title,url:href,snippet:''})}const snippets=[...html.matchAll(/class=["'][^"']*result__snippet[^"']*["'][^>]*>([\s\S]*?)<\//gi)].map(m=>stripHtml(m[1]));out.forEach((x,i)=>x.snippet=snippets[i]||'');return uniqBy(out,x=>hostOf(x.url)).slice(0,14)}catch{return[]}}

function fallbackCompany(facts,url){const base=(facts.title||hostOf(url)||'Business').replace(/\s*[|–—-].*$/,'').trim();const words=(facts.h1.concat(facts.h2).join(' ')+' '+facts.description).toLowerCase();const keys=[...new Set(words.split(/[^a-z0-9]+/).filter(w=>w.length>4&&!['about','contact','privacy','terms','learn','services','company','canada','ontario','toronto','their','with','from','your'].includes(w)))].slice(0,12);return {name:base||hostOf(url),description:facts.description||facts.h1[0]||null,territory:null,category:null,buyer_type:'business buyers',offers:facts.h2.slice(0,8),keywords:keys,employees:null,monthly_traffic:null,source_url:url}}

async function companyPhase(url){const pages=await crawlBusiness(url);const home=pages[0];const fallback=fallbackCompany(home.facts,home.url);const corpus=pages.map(p=>`SOURCE ${p.url}\nTITLE ${p.facts.title}\nDESCRIPTION ${p.facts.description}\nH1 ${JSON.stringify(p.facts.h1)}\nH2 ${JSON.stringify(p.facts.h2)}\nTEXT ${p.facts.text.slice(0,9000)}`).join('\n\n');const ai=await aiJSON(`Analyze this business for outbound planning. Read all source blocks.\n${corpus}\nReturn {"name":string|null,"description":string|null,"territory":string|null,"category":string|null,"buyer_type":"business buyers","offers":string[],"keywords":string[],"employees":null,"monthly_traffic":null,"source_url":"${home.url}"}. Do not estimate employees or traffic. Keep the description factual and concise.`);const publicEmails=[...new Set(pages.flatMap(p=>p.facts.emails))].slice(0,8);return {company:{...fallback,...(ai||{}),source_url:home.url},site:{url:home.url,research_pages:pages.map(p=>p.url),public_emails:publicEmails}}}

async function competitorsPhase(state){const c=state.company||{};const target=hostOf(c.source_url||state.url);const offer=(c.offers||[])[0]||'';const key=(c.keywords||[]).slice(0,3).join(' ');const queries=[`${c.category||offer||key} Toronto Ontario competitors`,`${key} GTA Ontario companies`,`${c.name||target} alternatives Toronto Ontario`];const batches=await Promise.all(queries.map(searchWeb));let results=batches.flat();results=uniqBy(results,x=>hostOf(x.url)).filter(x=>{const h=hostOf(x.url);return h&&h!==target&&!/(facebook|linkedin|instagram|youtube|yelp|wikipedia|reddit|duckduckgo|yellowpages)/i.test(h)}).slice(0,14);const ai=await aiJSON(`Target company: ${JSON.stringify(c)}\nSearch results: ${JSON.stringify(results)}\nReturn {"competitors":[{"name":string,"domain":string,"source_url":string,"rationale":string|null}]} using only supplied search results. Keep max 8 and prefer same-market competitors over directories or publishers.`);return {competitors:(ai?.competitors||results.map(r=>({name:r.title,domain:hostOf(r.url),source_url:r.url,rationale:r.snippet||null}))).slice(0,8)}}

function fallbackSegments(c){const cat=((c.category||'')+' '+(c.keywords||[]).join(' ')+' '+(c.offers||[]).join(' ')).toLowerCase();if(/law|legal|estate|will|probate/.test(cat))return ['Real estate brokerages','Mortgage brokerages','Accounting firms','Owner-operated businesses'];if(/loan|funding|finance|credit|capital|cash advance/.test(cat))return ['Owner-operated businesses','Multi-site operators','Referral partners','Business advisors'];if(/hvac|plumb|roof|electric|contract/.test(cat))return ['Property managers','General contractors','Multi-site operators','Commercial facility operators'];return ['Owner-operated businesses','Multi-site operators','Property managers','Referral partners']}

async function campaignsPhase(state){const c=state.company||{};const initial=fallbackSegments(c);const ai=await aiJSON(`Refine this supervised GTA B2B campaign plan. BUSINESS: ${JSON.stringify(c)}. INITIAL SEGMENTS: ${JSON.stringify(initial)}. REQUIRED GUARDRAILS: verified source URL per factual claim; suppression list; human approval; no homeowner cold outreach; no inferred email addresses. Rank up to four buyer segments. For each return fit_score, rationale, required_evidence, exclusion_rules, and one low-pressure first_touch_draft. Do not recommend automated sending. End with kill_criteria for the first 50 manually reviewed touches. Return {"campaigns":[{"name":string,"fit_score":number,"rationale":string,"required_evidence":string[],"exclusion_rules":string[],"first_touch_draft":string}],"kill_criteria":string[]}. Do not invent market sizes or response rates.`);if(ai?.campaigns)return ai;return {campaigns:initial.map((name,i)=>({name,fit_score:80-i*7,rationale:'Potential B2B segment to validate against public evidence before outreach.',required_evidence:['Relevant business activity from a public source URL','Published business contact path'],exclusion_rules:['Existing customers','Competitors','Do-not-contact records','Consumer/homeowner records'],first_touch_draft:'Hi — I came across your business while researching GTA companies in this segment. If this is relevant, I can send a short summary of how we may help. If not, I will close the loop.'})),kill_criteria:['Stop after 50 manually reviewed touches if fewer than 2 relevant replies','Stop any segment with repeated mismatch feedback','Pause immediately on compliance or deliverability concerns']}}

async function prospectsPhase(state){const c=state.company||{};const campaigns=(state.campaigns||[]).slice(0,4);const offer=((c.offers||[])[0]||(c.keywords||[]).slice(0,2).join(' ')||c.category||'').trim();const searches=[];for(const seg of campaigns){searches.push({segment:seg.name,q:`${seg.name} Toronto GTA Ontario ${offer}`});searches.push({segment:seg.name,q:`${seg.name} Ontario ${c.category||''}`})}const batches=await Promise.all(searches.map(async s=>(await searchWeb(s.q)).map(x=>({...x,segment:s.segment,query:s.q}))));let rows=batches.flat();const target=hostOf(c.source_url||state.url);rows=uniqBy(rows,x=>hostOf(x.url)).filter(x=>{const h=hostOf(x.url);return h&&h!==target&&!/(facebook|linkedin|instagram|youtube|yelp|wikipedia|reddit|yellowpages|mapquest)/i.test(h)}).slice(0,20);const ai=await aiJSON(`Business: ${JSON.stringify(c)}\nCampaigns: ${JSON.stringify(campaigns)}\nCandidate search results: ${JSON.stringify(rows)}\nReturn {"prospects":[{"name":string,"domain":string,"source_url":string,"segment":string|null,"fit_score":number,"why_fit":string|null}]} max 12. Use only supplied candidate URLs. Fit scores are analytical, not factual claims. Reject directories, publishers and obvious non-buyers.`);return {prospects:(ai?.prospects||rows.map((r,i)=>({name:r.title,domain:hostOf(r.url),source_url:r.url,segment:r.segment,fit_score:Math.max(55,88-i*2),why_fit:r.snippet||null}))).slice(0,12)}}

async function crawlProspect(p){const pages=await crawlBusiness(p.source_url);const corpus=pages.map(x=>`SOURCE ${x.url}\n${x.facts.text.slice(0,9000)}`).join('\n\n');const emails=[...new Set(pages.flatMap(x=>x.facts.emails))].slice(0,6);const ai=await aiJSON(`Find publicly evidenced B2B decision-makers from these company pages. Prospect: ${JSON.stringify(p)}\n${corpus}\nReturn {"people":[{"name":string,"role":string|null,"source_url":string}],"public_emails":${JSON.stringify(emails)}}. Never invent names, roles, LinkedIn URLs, or email addresses. If no person is explicitly present, return an empty people array.`);return {prospect:p,people:ai?.people||[],public_emails:emails,pages:pages.map(x=>x.url)}}

async function contactsPhase(state){const prospects=(state.prospects||[]).slice(0,8);const settled=await Promise.allSettled(prospects.map(crawlProspect));const contacts=[];for(const s of settled){if(s.status!=='fulfilled')continue;const x=s.value;const publishedEmail=x.public_emails[0]||null;if(x.people.length){for(const person of x.people.slice(0,2))contacts.push({company:x.prospect.name,domain:x.prospect.domain,name:person.name,role:person.role||null,email:publishedEmail,source_url:person.source_url||x.prospect.source_url,email_source_url:publishedEmail?x.pages.find(Boolean)||null:null,fit_score:x.prospect.fit_score})}else contacts.push({company:x.prospect.name,domain:x.prospect.domain,name:null,role:null,email:publishedEmail,source_url:x.prospect.source_url,email_source_url:publishedEmail?x.pages.find(Boolean)||null:null,fit_score:x.prospect.fit_score})}return {contacts:contacts.slice(0,12)}}

async function emailsPhase(state){const c=state.company||{};const contacts=(state.contacts||[]).slice(0,8);const out=[];for(const x of contacts){const ai=await aiJSON(`Write one low-pressure B2B first-touch email based only on these facts. Sender business: ${JSON.stringify(c)}. Prospect/contact: ${JSON.stringify(x)}. Return {"subject":string,"body":string}. Do not claim unverified pain, intent, results, urgency, or relationship. Keep under 90 words. Include an easy opt-out. This is for human review, not automated sending.`);const subject=ai?.subject||`Quick question for ${x.company}`;const body=ai?.body||`Hi${x.name?' '+x.name:''},\n\nI came across ${x.company} while researching GTA businesses that may fit what we offer. If this is relevant, I can send a short overview. If not, no problem — reply “no” and I will close the loop.\n\nBest,\n${c.name||'ReadyCustomer'}`;out.push({...x,subject,body,mailto:x.email?`mailto:${encodeURIComponent(x.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`:null})}return {emails:out,send_mode:'manual_review_required'}}

export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const started=Date.now();try{const {phase,url,state={}}=req.body||{};if(!phase||!url)return res.status(400).json({error:'phase and url are required'});let data;if(phase==='company')data=await companyPhase(url);else if(phase==='competitors')data=await competitorsPhase({...state,url});else if(phase==='campaigns')data=await campaignsPhase({...state,url});else if(phase==='prospects')data=await prospectsPhase({...state,url});else if(phase==='contacts')data=await contactsPhase({...state,url});else if(phase==='emails')data=await emailsPhase({...state,url});else return res.status(400).json({error:'Unknown phase'});return res.status(200).json({ok:true,phase,duration_ms:Date.now()-started,...data})}catch(e){console.error('scan error',e);return res.status(500).json({error:e?.message||'Scan failed',duration_ms:Date.now()-started})}}
